title: N1000g's blog # name of the site
author: n1000g # name of site's author
email: n0b1000g@gmail.com # email of site's author
url: https://n1000g.github.io # root address of the site
baseurl: "" # subpath of the site
description: > # description of the site (multiple lines allowed)
  worthless musings.

permalink: /:slug.html

favicon: "favicon.png" # name+extension of favicon (which must be put on the root folder)

remote_theme: riggraz/no-style-please 

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "home" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
